### PR TITLE
feat: Fixed tooltip

### LINKED ISSUE #315: The species tooltip in the observation inspector can get detached
### Steps to reproduce
1. Open the "Explore results" page and load a dataset.
2. Click a station on a map. A popup will appear with information about the station; the tooltip for species will automatically expand.
3. Click one of the photos to open observation inspector. The species tooltip will get detached and it will be displayed in the top left corner instead.

Screenshot from 2022-08-16 17-14-32

### Notes
We are currently using the deprecated `Tooltip` component; perhaps the newer `Tooltip2` will fix the issue.

### PR DESCRIPTION
**Pull request by oluwakemi-dada**
### Changes
Closes #315

### Description
* Migrated from the deprecated tooltip version to a newer version.

### How to test
* Run the app.
* Click on the marker.
* Hover on the species to display tooltip.

### CODE REVIEW

File: src/renderer/components/Map.tsx [hunk 1]
```diff
@@ -9,6 +10,7 @@ import { useTranslation } from 'react-i18next';
 import { EmptyClasses } from '../constants/animalsClasses';
 import AnimalsListTooltipContent from './AnimalsListTooltipContent';
 import styles from './Map.module.scss';
+import '@blueprintjs/popover2/lib/css/blueprint-popover2.css';
```
Comment (kamilzyla) [inline src/renderer/components/Map.tsx:13]: Let's keep the imports organized in two groups separated by a blank line: external packages and app-specific imports. Inside each group let's keep the imports organized alphabetically (press Shift + Alt + O to "Organize Imports" in VSCode).

With this convention it is obvious where each import should go and the diffs are easier to review. :slightly_smiling_face:

**Review by kamilzyla — APPROVED** [review]
LGTM, this fixes the issue! :+1: :tada: Feel free to merge after you consider my comment.

File: src/renderer/components/Map.tsx (hunk 1 above)
Comment (oluwakemi-dada) [reply src/renderer/components/Map.tsx]: I just fixed it. Thank you for the shortcut 🙂
